import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int counter2, counter3, counter4;
		int counter = 0;
		double bigCounter = 0;
		counter2 = 0;
		counter3 = 0;
		counter4 = 0;
		bigCounter = 0;
		for (int i = 0; i < T; i++){
			int gender = (int)(generator.nextDouble()*2);
			if (gender == 1){
				while (gender == 1) {
					counter ++;
					gender = (int)(generator.nextDouble()*2);
				}
				gender = 2;
				counter++;
			}
			if (gender == 0){
				while (gender == 0) {
					counter ++;
					gender = (int)(generator.nextDouble()*2);
				}
				gender = 2;
				counter++;
			}
			if (counter == 2){
				counter2++;
			}
			if (counter == 3){
				counter3++;
			} 
			if (counter >= 4){
				counter4++;
			}
		bigCounter += counter;
		counter = 0;
	}
	double avarage = bigCounter/T;
	System.out.println("Average: " + avarage + " children to get at least one of each gender.");
	System.out.println("Number of families with 2 children: "+ counter2);
	System.out.println("Number of families with 3 children: "+ counter3);
	System.out.println("Number of families with 4 or more children: "+ counter4);
	int maxCounter = Math.max(counter2, counter3);
	maxCounter = Math.max(maxCounter, counter4);
	if (counter2 == maxCounter){
		System.out.println("The most common number of children is 2.");
	}else if (counter3 == maxCounter) {
		System.out.println("The most common number of children is 3.");
	}else{
		System.out.println("The most common number of children is 4 or more.");

	}
	}
}




